name: hello world

env:
  USERNAME: "sauravsarkar"

on:
  workflow_dispatch:
    inputs:
      username:
        description: "A username passed from the caller workflow"
        default: "john-doe"
        required: false
        type: string

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show System Information
        run: |
          echo "Run multiple lines of code $(uname -a)"
          echo "Kernel version $(uname -r)"
          echo "Current user is $(whoami)"
          echo "OS: $RUNNER_OS"
          echo "Arch: $RUNNER_ARCH"

      - name: Run a one-line script
        run: echo "Hello world"

      - name: Show current date
        run: date

      - name: Print the input name to STDOUT
        run: echo "The username is ${{ inputs.username }}"

      - name: Print the username to STDOUT
        run: echo "The username is ${{ env.USERNAME }}"

  checkout-example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show last commit details
        run: |
          echo "Last commit:"
          git log -1

      - name: Show last commit message
        run: echo "Last commit message:$(git log -1 --pretty=%B)"

      - name: Show full diff between last 2 commits
        run: |
          echo "========== LAST 2 COMMITS DIFF =========="
          git diff --name-status HEAD~1 HEAD
          echo "========================================="

      - name: Display files in the repository
        run: ls -la
